server:
   port: 8181

logging:
    path: logs
    file: mylog.log


spring:
   application:
          name: report
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3306/test
       username: root
       password: root

mybatis:
    type-aliases-package: com.test.course
    mapper-locations:
       - mapper/*

